### ISSUE TITLE
As a returning existing user, I need to be routed to the onboarding flow or roadmap based on status

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#180]
Based on user flows in #179.

Activities include:

- [x] ask myNJ folks to change our redirect URL to /roadmap
- [x] change our AWS redirect URL to /roadmap
- [x] Write code in /roadmap page that a user should be redirected to /onboarding if they have not yet completed onboarding
- [x] Add "Log In" button in the hero section
- [x] I should not see the landing page after logged in.

**Comment by guy-nj** [comment]
Currently I am seeing this Log Out button on the landing page after logged in. I should be brought to onboarding. I have added this issue as " I should not see the landing page after logged in." in the story.

<img width="833" alt="Screen Shot 2021-07-09 at 1 35 45 PM" src="https://user-images.githubusercontent.com/77984966/125131877-7de6da80-e0d1-11eb-95f7-e577a80e0253.png">

**Comment by aloverso** [comment]
@guy-nj @skeeJay Question about " I should not see the landing page after logged in."

I've been assuming the following:
- If I visit the landing page and I _have_ completed onboarding, I am redirected to /roadmap
- If I visit the landing page and I _have not_ completed onboarding, I am redirected to /onboarding

However, there is a real possibility that the user visits the landing page and the browser knows that they are logged in to the application, but our API call to fetch their data fails, and we don't know if they have or have not yet completed onboarding.

What should we do in that situation?

**Comment by guy-nj** [comment]
@aloverso I guess we can only choose if the user in that scenario should be brought to the landing page or onboarding. I would say bringing the user to the onboarding step 1 could be the safer solution. Thoughts?

Do we have another API call or data return when the user has visited the roadmap page? So we have one more identifier to know where the user is.

**Comment by skeeJay** [comment]
I agree, it's kind of a Sophie's choice because neither is perfect for that situation. But it's the kind of thing we can tweak in the future with a future user story.

**Comment by aloverso** [comment]
@guy-nj yes, we do fetch their data on roadmap, so this situation would be more uncommon (user going directly to landing page and the API call failing).

Maybe navigating to roadmap would be a good choice? Here's my rationale:
- it's more likely that they've already finished onboarding
- if they go to roadmap, and the API call succeeds, and they have a roadmap, they'll see it
- if they go to roadmap, and the API call succeeds, and they haven't onboarded, they'll get redirected to onboarding (that's already part of our functionality
- if they go to roadmap, and the API call fails, we'll show a "sorry something went wrong" error and there's not to be done there anyways

**Comment by aloverso** [comment]
Sounds good. @maitanavarro you want to take this one? The task would be: on the landing page, if we get an error back from loading user data, it should redirect to /roadmap (right now, we're just not doing anything at all if we don't know their userData form progress)

**Comment by skeeJay** [comment]
@guy-nj You and I should both try to QA.

**Comment by guy-nj** [comment]
It looks good on both Windows and Mac. But I haven't tested the return-onboarding scenario.

**Comment by skeeJay** [comment]
@aloverso Please see Guy's question. We may need you to delete his selections so he can test this.

**Comment by guy-nj** [comment]
So this is what I tried: I went back to onboarding and deleted my municipality selection and waited for being logged out. This is what I see when logged back in. I am landing on Roadmap and seeing Location as Not Set. Is this the right behavior or should I be redirected to Onboarding? Would this scenario be the same as the net-new user who hasn't onboarded? 
<img width="1027" alt="Screen Shot 2021-07-20 at 9 59 45 AM" src="https://user-images.githubusercontent.com/77984966/126337718-629b627f-89fc-4f8e-812b-c023ea0eec85.png">

**Comment by aloverso** [comment]
You can tell me if we should change this logic, but right now the only way to test the return-onboarding is to create a new account. As soon as you complete your onboarding form the first time, it's considered "completed" and then you'll get redirected to roadmap from there on out.

**Comment by skeeJay** [comment]
@aloverso I don't think that user logic should change, but I'm curious how hard it would be for you to simply delete Guy's selections from his account so he can test without needing a new account.

**Comment by aloverso** [comment]
@skeeJay @guy-nj I reset both of your onboarding-form progress. next time you sign in, you should be redirected to the onboarding flow. And if you visit the landing page (before completing the onboarding flow), you should get redirected back to onboarding

**Comment by skeeJay** [comment]
Seems to work as expected; @guy-nj, let us know.

**Comment by guy-nj** [comment]
It looks good. Although I saw Roadmap for 1 sec and then it jumped to Onboarding - I guess that was cache? Anyway it works!

**Comment by skeeJay** [comment]
@guy-nj I believe that's expected behavior, based on the fact that myNJ directs initially to Roadmap and then it's up to Roadmap to detect Onboarding status and direct the user back to Onboarding.

**Comment by aloverso** [comment]
@skeeJay yes that's correct

**Comment by guy-nj** [comment]
Sounds good. I am moving to Ready to deploy to staging.
