### ISSUE TITLE
As Poppy, I need to see additional status types on license Task screen

### ISSUE THREAD

**Issue by guy-nj** [newjersey/business.nj.gov#182]
Activities include:

- [x] We need to map all possible license statuses in the database:
  - Active
  - Pending
  - Expired
  - Barred
  - Out of Business
  - Reinstatement Pending
  - Closed
  - Deleted
  - Denied
  - Voluntary Surrender
  - Withdrawn

### Todo:

- [x] Backend should return the status of the _most recent_ entry that we get back from searching license statuses
- [x] Frontend should apply Grey Theme to any status that is not Active or Pending 
- [x] [Design QA] Change the green checkmarks to grey (same grey as the exclamation) for grey theme's application item list. 

### Dev notes:

Frontend:

- [x] We control all the theme components with the PermitThemes defined in `LicenseStatusReceipt`
- [x] The theme values are css classes. If they don't exist in njwds, we create them in `license-status.scss`
- [x] Most of the receipt component assumes the status is only either Active or Pending, this needs to be fixed all over the component
- [x] LicenseStatus type will now only be used on LicenseStatusItems (checklist items). A new type will be needed to represent the overall LicenseStatus, which will have to expand to include a dozen more statuses

Backend:

- [x] LicenseEntity type should allow any string as the license status
- [x] LicenseStatus type will now only be used on LicenseStatusItems (checklist items). A new type will be needed to represent the overall LicenseStatus, which will have to expand to include a dozen more statuses
- [x] Write a db migration for the new userData types (because of new license statuses) even though the migration won't have any logic in it
- [x] in `searchLicenseStatusFactory`:
  - [x] `const match = entities.find...` should find the MOST RECENT license in there, according to spec below
  - [x] `const match = entities.find...` allow finding an expired license if that's the most recent one
  - [x]  will need to use dayjs to parse the datestring in the weird format that we get from boomi
  - [x]  `status: match.licenseStatus === "Active" ? "ACTIVE" : "PENDING",` will now need to figure out from `match.licenseStatus` what the actual status should be (yknow one of like 12 options or something)
- [ ] "most recent" can be determined by the date of the record. If it has an `issueDate`, use that. If not, use `dateThisStatus` (which needs to be added to the Entity type). If it does not have that, use `expirationDate`.

**Design**
1. Use the exact status from the database to show in our Permit Status (for now).
2. For "Grey theme" statuses, the task status would display "NOT STARTED".
3. The task status would display "PENDING" for "Reinstatement Pending" application status.
- [x] [Green theme](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=0%3A1&node-id=3698%3A55988&viewport=-5886%2C-780%2C0.25038909912109375&scaling=min-zoom&starting-point-node-id=2787%3A6429&show-proto-sidebar=1) for Active
- [x] [Blue theme](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=0%3A1&node-id=2227%3A30532&viewport=-5886%2C-780%2C0.25038909912109375&scaling=min-zoom&starting-point-node-id=2787%3A6429&show-proto-sidebar=1) for Pending, Reinstatement Pending
- [ ] [Grey theme](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=0%3A1&node-id=3698%3A56410&viewport=-5216%2C-593%2C0.2294345200061798&scaling=min-zoom&starting-point-node-id=18%3A30&show-proto-sidebar=1) for Expired, Barred, Out of Business, Closed, Deleted, Denied, Voluntary Surrender, Withdrawn

**Comment by guy-nj** [comment]
@skeeJay I have added the notes above per our discussion. Please add more if anything is missing.

**Comment by aloverso** [comment]
@skeeJay @guy-nj previously our logic was to show "license not found" if the only status we can find for their information was "Expired"

for what it's worth, I think it's better for the user to get the Grey Theme when their search comes back with "expired" instead of being told Not Found (which is not exactly accurate), but I just wanted to confirm that this change in logic was intentional

**Comment by guy-nj** [comment]
Is Expired the only status that we will display in the Grey Theme for Poppy MVP? @skeeJay

**Comment by skeeJay** [comment]
@guy-nj I am not sure I understand exactly what you're asking.

The color of the theme should always exactly map the Task status that it is triggering: NOT STARTED, IN PROGRESS, and COMPLETED. In a nutshell, I think that any status that requires a submission for the user to get back to ACTIVE should be gray/NOT STARTED, and any status that they are merely waiting on should be blue/IN PROGRESS. The key differentiator is whether a new submission triggering a new process by the user is required. Does that answer your question?

**Comment by guy-nj** [comment]
So I listed these statues as [Grey theme](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=0%3A1&node-id=3698%3A56410&viewport=-5216%2C-593%2C0.2294345200061798&scaling=min-zoom&starting-point-node-id=18%3A30&show-proto-sidebar=1):  Expired, Barred, Out of Business, Closed, Deleted, Denied, Voluntary Surrender, Withdrawn in the story description (in Design section). Just wanted to double check that are we showing all these statuses, or just Expired status for MVP?

**Comment by skeeJay** [comment]
As this ticket is written, I believe we're planning to show all 11 statuses as reported by the database. Right?

**Comment by guy-nj** [comment]
Sure. Also yes to Anne's Expired logic question above. We will show the grey theme when the search comes back with Expired.

**Comment by guy-nj** [comment]
Added the design QA note of changing green checkmarks to grey in the Todo section.

**Comment by skeeJay** [comment]
@guy-nj Can you QA this?

**Comment by guy-nj** [comment]
Looks good! 2 questions:
1. I kept getting error message when trying to search this Deleted status: A & S CONSTRUCTION, 157 Beach Street, 07307. Does anyone see the Deleted result successfully? 
2. There are two unchecked items in Todo section in the story. Are they still in progress?

**Comment by aloverso** [comment]
I also don't get data for that one. I went and looked directly in the database and I cannot find that company there anymore. Perhaps the test data has changed since I made that sample-file? Or perhaps I made a copy-paste error on that one?

**Comment by maitanavarro** [comment]
1. Yeah I didn't see data for that either, maybe it has changed. 
2. Just updated the Todo section! They aren't in progress.

**Comment by guy-nj** [comment]
It sounds good to me. I think the Deleted status shouldn't be the blocker for this. We can test it when we find another Deleted case. @skeeJay I am good moving this to Ready to deploy to staging.
