### ISSUE TITLE
General research/planning for compliance/annual filings on Poppy's Roadmap

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#204]
Pending spec from @Jesslax. Focus: Income tax filings for three legal structures: Sole proprietor, general partnership, and single-proprietor LLC

Activities include:

- [ ] Executive Summary of Existing Research
- [ ] Stakeholder Questions
- [ ] Stakeholder Interviews
- [ ] Research Plan
- [ ] Recruit User/Agency Research Participants
- [ ] Conduct User/Agency Research
- [ ] Synthesize Research
- [ ] Solution Brainstorming
- [ ] Feasibility Assessment
- [ ] Design
- [ ] Prototyping
- [ ] Usability Testing
- [ ] Iteration
- [ ] Dev Handoff
- [ ] Development
- [ ] Testing
- [ ] Release

**Comment by aaronvux** [comment]
Income Tax Research:
https://docs.google.com/document/d/1AWWtgF1t1LsIeWlvVGn6CkOAkVzQAdITvuTnNSeOi6o/edit?usp=sharing
