### ISSUE TITLE
Content & Design: Develop first iteration of Operate section containing Annual Report and Income Tax

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#390]
Goal: Understand what MVP of taxes and filings should be
- [ ] Ask Treasury for a list of all fields and values of taxpayer eligibility profiles @Jesslax 
- [ ] Ask Treasury to inform us the impact values have on the user (doing as 2 separate asks to not overwhelm them)
- [ ] Do user research to understand what businesses owners need to know about taxes and filings -How are users currently learning what taxes to file? How are users filing those taxes?
Do they have help? Which type of tax are users having most the most trouble with?
- [ ] Update designs of Operate/Filing sections for interim/first iteration

How do we know Poppy is shifting to Oscar?

How will the roadmap change when the user type changes?

**Comment by carye3** [comment]
- How do we know Poppy has become Oscar?
-

**Comment by carye3** [comment]
Notes: this is "operate for poppy"
