### ISSUE TITLE
Introduce Sections to Roadmap for existing Steps

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#422]
**As** Poppy
**I need to** see my Roadmap Steps broken into "Plan" and "Start" sections
**So that** I can see my Roadmap broken into further "phases" that can be collapsed when I move onto another phase of my business's lifecycle.

## Acceptance criteria

All users should receive a plan and start section.

## Notes

- [x] Steps fall within Sections, and need to be editable by Jess in terms of which Section they are in and the Order within each Section.
- [x] Steps retain their "global" numbering within each Section. If the "Plan" Section has Steps 1 and 2, then the "Start" Section starts with Step 3. [updated by @skeeJay after design review discussion]

~~- [ ] Plan and Start should both be expanded by default. They should be collapsible by the user, and the Roadmap should remember the state of whether each is collapsed **in the home roadmap screens (desktop & mobile)** (not in sidebar roadmap).~~ Addressed in #439

- [x] These will need to be integrated into the mini-roadmap on Task screens as well. (@carye3 This may need design.)

~~- [ ] Initially, place the existing Step "Plan Your Business" In the Plan Section and the other 4 Steps in the Start Section.~~ Step 1 and 2 will fall in plan section as per the design

- [x] Steps 1 and 2 should fall in the plan section.
- [x] Steps 3-5 should fall in the start section.
- [x] @carye3 will attach needed designs.

**Comment by carye3** [comment]
Jess: add onboarding step, ask them if they’re operating only

**Comment by Jesslax** [comment]
@skeeJay right now we dont have information to put under operate. So I dont want it to be built, a user goes in and then sees no information in the operate section. For this tkt, should I write conditions for the current scenario, or the scenario where we have content under the operate section?

**Comment by skeeJay** [comment]
@Jesslax This ticket doesn't introduce "Operate" at all. The description only refers to introducing "Plan" and "Start" sections. So let's stay limited to that: we're taking the existing Steps and splitting them between "Plan" and "Start" sections.

**Comment by skeeJay** [comment]
@carye3 Since we're not introducing "Operate" at all in the scope of this ticket, this shouldn't require any new onboarding questions. I think adding to Onboarding is for a far future epic, after we've introduced "Operate" for Poppy.

**Comment by carye3** [comment]
@skeeJay @mikewolfd @aloverso @FarazA22 for your review:

[Desktop](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=4930%3A110434)
[Mobile](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=4933%3A113927)

(Mini roadmap coming)

**Comment by carye3** [comment]
@Jesslax there's content for each section's subheading based on biz.nj.gov that's ready for your review too:

- Plan: "You’ve come up with a great idea and want to turn it into a great business."
- Start: "You’ve decided to start a business and now it’s time to legally register it."

**Comment by carye3** [comment]
[Mini roadmap complete](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=4941%3A111519)

**Comment by Jesslax** [comment]
@carye3 looks clean! Should the #4 step be equidistant between 3 and 5?

**Comment by carye3** [comment]
Thx @Jesslax -- fixed

**Comment by aloverso** [comment]
@carye3 going forward, could you add the design links to the story description? makes them easier to find than scrolling through comments. thanks!

**Comment by aloverso** [comment]
@skeeJay @carye3 noticed the the story notes say " Step numbering starts over within each Section. For example, the "Plan" Section can have a Step 1, and then the "Start" Section has its own Steps 1–4" 

But in the designs, the steps stay sequential 1-5 across sections

Which is desired?

**Comment by skeeJay** [comment]
cc @Jesslax also on the above question. @carye3  maybe we can discuss briefly at the design review. I don’t have a string inclination right now either way, but maybe the future plans for Operate or @Jesslax ’s understanding of the business journey can point us towards one or the other.

**Comment by skeeJay** [comment]
This is looking pretty slick to me. @carye3 do you want to put eyes on it before we deploy?

**Comment by carye3** [comment]
Looks good!

FYI I'm going to be adding a design ticket soon regarding the coloring & size of section / step icons
