### ISSUE TITLE
As Poppy, I need to see a visual treatment of the roadmap screen, so that I can understand which tasks are in progress or completed

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#43]
**Design**
[Prototype](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=90%3A4&viewport=-180%2C63%2C0.07508362829685211&scaling=min-zoom)
[Figma](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=90%3A4)

**User Actions**
As Poppy,
1. Under the page title, I see a box with my business info that I input in the previous "Input Info" step. Clicking "Edit" brings me back to the beginning of the "Input Info". If I change anything in Input Info, the roadmap would be regenerated accordingly and all tasks will be reset to "Not Started" (@aloverso @skeeJay to confirm the reset function). 
2. I see a vertical progress bar on the left side of the screen indicating how many Steps are in my roadmap. Clicking on the step number/title brings me to Tasks screen of the first uncompleted task in that step. (@skeeJay @aloverso or bring to the very first task in that step?)
3. I see a list of tasks under each step. Clicking a task title brings me to Task screen where I can learn more detail about how to complete the task.

4. I can also understand my progress of each step by reading the line "X/N tasks completed" under the Step Title.

**Mobile/Tablet Experience**
There is no mobile side-nav for this screen.
[Mobile Mock](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=497%3A0&viewport=406%2C1144%2C0.4218480885028839&scaling=min-zoom)
[Mobile Figma](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=488%3A3970)

## work needed
- [x] The h1 should be "Business Roadmap for [Business Name]". (UPDATED)
- [x] The paragraph below the h1 should be a larger font size, per design.
- [x] Number in each Step circle looks like it should be slightly larger font size, per design. (PLEASE OVERRIDE STYLE GUIDE)
- [x] Textual time estimates for each step should us en dash instead of hyphen. They should have a darker gray color, per design.
- [x] Step names, Step description, and Task names should have lower font weight, per design. (This may be related to font family.)
- [x] The step number, step title, and step description should be top aligned.
- [x] Step title should be 16px- Step estimate time should be 13px 
- [x] Step description should be 16px (need to set $theme-body-font-size: "sm")
- [x] Task title/link should be16px
- [x] "Edit" in the business info box is 16px

**Comment by aloverso** [comment]
@skeeJay @guy-nj I think that #4 on this list ("X/N tasks completed" under the Step Title) should be reconsidered or moved to a different feature story? I seem to recall us having some conversations about maybe other ways to represent this? Either way, I think it should be considered a new feature instead of a visual treatment, since it does not currently exist

**Comment by skeeJay** [comment]
@aloverso A question as I look at this user story for validation: it's clear there is a difference between the fonts used by @guy-nj on the attached design. Is that because Guy's design did not use fonts available in our style guide, or for another technical reason? (Screenshots attached)

Design:
<img width="1312" alt="Screen Shot 2021-03-11 at 11 41 11 AM" src="https://user-images.githubusercontent.com/506096/110822122-c0e98c00-825e-11eb-8a0d-7f52dae2611b.png">

Developed:
<img width="1399" alt="Screen Shot 2021-03-11 at 11 41 18 AM" src="https://user-images.githubusercontent.com/506096/110822128-c2b34f80-825e-11eb-8bbd-33cdbbcba90b.png">

**Comment by skeeJay** [comment]
@aloverso Below are some of my notes from my review… as discussed, excluding font family for now, but I believe these below are design elements that should not conflict with other parts of the style guide (e.g., font size and font weight), but let me know if any of them do (e.g, indent distance of bullets, etc.)

1. The h1 appears from the design that it should be “[user’s first name]’s Business Roadmap” not “[business name] Roadmap.” Sorry if this was unclear and should have been in acceptance criteria.
2. The paragraph below the h1 should be a larger font size, per design.
3. Number in each Step circle looks like it should be slightly larger font size, per design.
4. Textual time estimates for each step should us en dash instead of hyphen. They should have a darker gray color, per design.
5. Step names, Step description, and Task names should have lower font weight, per design. (This may be related to font family.)
6. The dot for each task bullet under each step should have no indent distance itself and should be left aligned with the Step descriptions text, per design. (I am unsure if this would conflict with what is prescribed by the style guide for unordered lists, but I don't think it would.)

cc @guy-nj @Jesslax particularly Guy to check me on some of these visual tweaks.

**Comment by aloverso** [comment]
1. I thought that the naming criteria for "Joe's Business Roadmap" was "[business name]'s Roadmap" as in, Joe's Business was the name of the business. Which is it that we actually want to show? One thing to consider is @guy-nj's new onboarding flow that, if I recall, does not actually collect the user first name any more? We can show whichever but we should make a conscious decision

2 & 6 - I can definitely do this easily, but this would be overriding the styles of that the styleguide provides (either, for the bullet items or for the vertical stepper). Again, absolutely possible, just want us to be aware of where we're diverging

3, 4, 5 make sense

**Comment by guy-nj** [comment]
@skeeJay my understanding is also [Business Name] rather than [User Name]. 

@aloverso Let me know if there is any issue in the Figma files.

**Comment by skeeJay** [comment]
One problem with "[business name]'s Roadmap" is in the example of my screenshot below, where my diner is named "E.J.'s" and the title is "E.J.'s's Business Roadmap." (with two apostophe-S-es).

So we'd have to structure it as either "[The] [business name] Business Roadmap" (e.g., "Walmart Business Roadmap") or "[business owner first name] Business Roadmap" (e.g., "E.J.'s Business Roadmap." The first is more impersonal, and based on the business identity, and will change if they go back and edit their business name. The second is more personal, and won't change if they change their mind, because their personal name remains the same.

So what's more important, business identity or getting personal with the owner? Might be a question for @Jesslax.

**Comment by skeeJay** [comment]
@guy-nj Let us know about Anne's notes for items 3 and 6: should she override the style guide?

**Comment by guy-nj** [comment]
@skeeJay @aloverso Yes please override to the item 3. 

As for item 6, I am okay with how it looks on the current staging. I tend to stay with how the default bullet point is handled since this might affect all bullet points everywhere on the site.

Regarding, agreed that we need a better copywriting structure to accommodate the unpredictable business name. I personally think "'[Business Name]' Business Roadmap" or "Business Roadmap for [Business Name]" works well.

**Comment by skeeJay** [comment]
If we're going with the business name, I think "Business Roadmap for [Business Name]" avoids many more grammatical minefields, and that's probably what we should go with. cc @Jesslax

**Comment by Jesslax** [comment]
E.J.'s roadmap sounds more colloquial and friendly to me. The problem you raise is a good one. Let me see if I can think of anything else, otherwise that's a good solution.

**Comment by skeeJay** [comment]
@Jesslax To get more explicit, you are voting for [user’s first name], correct? I think we need to form a consensus on one side or the other, for now at least.

**Comment by guy-nj** [comment]
Can we get the user's first name from the login?

**Comment by guy-nj** [comment]
Sorry I closed it by accident. The "Close with comment" button is terrible - I thought that was "Cancel".

**Comment by Jesslax** [comment]
No worries Guy.
@skeeJay I am voting for Joe's Roadmap, I think it's more friendly. IF we can find a work around for the grammatical minefields.

**Comment by skeeJay** [comment]
@Jesslax Hah I'm still a little unclear what you mean, because Joe can be his first name or "Joe's" could be the name of his diner. Let's discuss at standup.

**Comment by Jesslax** [comment]
Sorry! I think it should be the <Name of business>'s Roadmap.

**Comment by skeeJay** [comment]
Okay, final decision: "Business Roadmap for [Business Name]" cc @aloverso

**Comment by skeeJay** [comment]
Thanks @aloverso , this is looking fabulous. A couple additional notes:

1. The paragraph below the h1 should have slightly more bottom padding/spacing with the gray box.
2. The Step description body text, as well as the Task unordered list bullets, look like they should have higher line-height, per the design. My eye can't tell from the Figma mock, but it also appears that all this text might want a lighter font-weight, but @guy-nj can tell us for sure.

Those are both minor. This is looking awesome!

**Comment by aloverso** [comment]
Fixed the spacing. Waiting to hear about line-height. The font is currently the lightest weight for Public Sans. Are we still deciding about font to go with, based on Dave's comments?

**Comment by skeeJay** [comment]
I wouldn’t touch the font family for now. The app pulled from the design which pulled from the style guide. If we want to change the style guide, it’s something we can talk about, but we should go back through design before changing the app

**Comment by skeeJay** [comment]
@aloverso Adding the "needs work" label based on the line-height for the bullets, like we just talked about, and also rolling this to sprint 6.

**Comment by skeeJay** [comment]
@aloverso Also the font.

**Comment by skeeJay** [comment]
@guy-nj This should be looked at from a design QA perspective now.

**Comment by skeeJay** [comment]
@guy-nj This is ready for design QA again.

**Comment by guy-nj** [comment]
The design looks good to me!
