### ISSUE TITLE
Operate Section (V1): Add calendar with annual filing deadline to Operate Section

### ISSUE THREAD

**Issue by carye3** [newjersey/business.nj.gov#533]
**As** Poppy
**I need to** understand basic annual reporting and income tax requirements for my business
**So that** I can stay in compliance once my business is running

## Design

[Operate: Calendar](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=5764%3A109126)
![image](https://user-images.githubusercontent.com/62653834/137328003-6f4c79b2-3c52-4fd4-af04-02e5f9aec58b.png)

[Operate: Calendar Mobile](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=5764%3A108910)
![image](https://user-images.githubusercontent.com/62653834/137328613-2a4564d3-cf00-41ae-9065-b48b1455fe0a.png)

[Contextual Info: Calendar - Next 12 Months](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=5392%3A121593)

## Acceptance criteria

**Given** The user has completed the Operate section prompt (see #527)
**When** the Operate section's content loads the calendar view
**Then** the calendar displays a Annual Report due task for the current calendar year on the same day and month of the business formation date.

**Given** The user has is viewing the calendar
**When** the user clicks the Annual Report filing date listed in the calendar
**Then** nothing happens for right now.

**Given** The user has is viewing the calendar
**When** the user clicks the Annual Report filing date listed in the calendar
**Then** nothing happens for right now.

**When** viewing the calendar
**Then** The calendar starts with the current month and extends out 12 months for desktop view and 4 months for mobile view.

**Given** viewing operate calendar view
**When** user selects "what happens if..." link
**Then** a contextual menu pops up
![image](https://user-images.githubusercontent.com/62653834/135494866-a4b57b9c-f50b-42d9-8c54-c977a63ef724.png)

**Given** viewing operate calendar view
**When** user clicks the questionmark next to calendar header
**Then** a contextual menu pops up
- Content:
  - This is your personalized calendar of upcoming of taxes and filings that the New Jersey Department of Treasury has identified. Click on any of the items to learn about the tax and where you can pay.
![image](https://user-images.githubusercontent.com/62653834/135494759-6a2b9deb-45b6-47a2-abfa-6fa9fed735cc.png)

## Notes

- [ ] Goal: Understand what MVP of taxes and filings should be
- [ ] Ask Treasury for a list of all fields and values of taxpayer eligibility profiles @Jesslax 
- [ ] Ask Treasury to inform us the impact values have on the user (doing as 2 separate asks to not overwhelm them)
- [ ] Do user research to understand what businesses owners need to know about taxes and filings -How are users currently learning what taxes to file? How are users filing those taxes?
Do they have help? Which type of tax are users having most the most trouble with?
- [ ] Update designs of Operate/Filing sections for interim/first iteration

**Comment by skeeJay** [comment]
@carye3 I believe yesterday we talked about this being the second ticket, meaning it would be built before #534 and thus its acceptance criteria should probably say that clicking the filing date does nothing, because the Task won't exist yet. That link should be added as acceptance criteria in #534 instead. Does that make sense?

**Comment by carye3** [comment]
yep. we've updated acceptance criteria to address that @skeeJay

**Comment by skeeJay** [comment]
@carye3 Okay. I think we just also need to update the acceptance criteria on this ticket to _remove_ the clicking functionality, since the Task screen won't exist yet.

**Comment by carye3** [comment]
@skeeJay got it -- removed

**Comment by carye3** [comment]
@Jesslax do you have content for "What happens if I don't submit my annual filings?" contextual menu

**Comment by Jesslax** [comment]
@carye3 yes I do, I usually go in and add/edit copy after it's setup.

**Comment by aloverso** [comment]
@carye3 I remember when we talked about this, we said that for the first pass, we could have the mobile view show all 12 months instead of just 4, so that we don't have complexity around when to show/hide the arrow buttons. Is that correct and if so, can we update the acceptance criteria?

**Comment by aloverso** [comment]
@skeeJay @carye3 @aaronvux we talked about making the arrow-buttons another story. Did that get a placeholder story? Should it be worked on before or after v2?

**Comment by carye3** [comment]
Designs updated @aloverso

**Comment by aaronvux** [comment]
This look good to me on desktop and mobile.  @skeeJay ready to staging?

**Comment by skeeJay** [comment]
@aaronvux Since it's been tweaked and modified considerably since moving into review, it seems to me like it's appropriate to get @Jesslax and @carye3's eyes on it again, to make sure it matches their understanding of what will go in front of the user, as well.

**Comment by aloverso** [comment]
@carye3 styling that you pointed out has been fixed

**Comment by Jesslax** [comment]
@aloverso Can I change the copy on these pages?

When I click the edit button in the calendar screen, it brings me to the Date of Business Formation screen. If I don't want to update my business formation date, I click on the back button in my web browser, but it does not bring me back to the calendar page. Curious as to why. Thanks!
