### ISSUE TITLE
Topic Page Templates (Hi-Fi & Mobile)

### ISSUE THREAD

**Issue by carye3** [newjersey/business.nj.gov#635]
- [ ] Contents list -- apply to all pages
- [ ] Divider style: beginning, end of list and between accordions -- apply to all
- [ ] Expandable tiles -- apply to all (or wait to hear back from accessibility ppl)
- [ ] Apply new icons to every page

Future Version:

- [ ] Test: No sidebar

Notes:
- Emulate SBA and Wikipedia

**Comment by kmelefsky** [comment]
@fiorella-io  checking in to see if there's any update here and if it's living in the right swim lane - thx!

**Comment by carye3** [comment]
@kmelefsky this is done
