### ISSUE TITLE
Update Brought to you by section on business.nj.gov Home page

### ISSUE THREAD

**Issue by aaronvux** [newjersey/business.nj.gov#654]
As a NJ Business Owner, I need to be able to understand the entities who are providing me information about managing my business so that I am well informed.

## Tasks

- [ ] Seal on left: Office of the Governor
- [ ] NJ logo on the far right: "Office of Innovation"
- [ ] Send to Kai for final approval

## Acceptance criteria

TBD

## Designs
Attach desktop and mobile designs here

## Notes

- [ ] UX Review
- [ ] PO Approval
