### ISSUE TITLE
Prepare Final Designs & Style Guide for Implementation

### ISSUE THREAD

**Issue by carye3** [newjersey/business.nj.gov#675]
## Tasks

- [ ] Schedule Joe story writing 10.26.21
- [ ] Prep User Stories for Joe Pt 1
  - [ ] Topics Landing Page
  - [ ] Topics Sub-Pages
- [ ] Provide Joe with prototype links
- [ ] List remaining pages for redesign (see Site Map #740 )
- [ ] Prep Mobile Version
- [ ] Prep User Stories for Joe Pt 1
  - [ ] COVID
  - [ ] Homepage

**Comment by kmelefsky** [comment]
@carye3  checking in to see if there's any update here and if it's living in the right swim lane - thx!

**Comment by carye3** [comment]
Yep all done @kmelefsky -- moving to resolved
