### ISSUE TITLE
Ad Hoc Biz.NJ Design Support

### ISSUE THREAD

**Issue by carye3** [newjersey/business.nj.gov#761]
- [ ] Topics landing page: 
  - [ ] list view in mobile
  - [ ] Fund & Navigator ad featured once at the top
- [ ] Funding icon (solid version)
- [ ] OPTIONAL:
  - [ ] Homepage redesign for mobile (no tiles?)
