### ISSUE TITLE
Desk Research: Oscar Experience - Service Blueprint

### ISSUE THREAD

**Issue by carye3** [newjersey/business.nj.gov#940]
## Research Tasks

- [x] Brain dump with Jess 
- [x] Schedule BAC review of SB
- [ ] Desk research based on gaps in knowledge
  - [ ] Request PBS accounts
  - [ ] SBA.gov
  - [ ] Jess' Notes: Download
  - [ ] Jess: #738 
  - [ ] Jess: #739 
  - [ ] Biz.NJ
  - [ ] Legalzoom
  - [ ] SBDC's
  - [ ] PBS account
- [ ] Create a rough "current state" service blueprint
- [ ] Feedback from BAC / Don on service blueprint
- [ ] Ideation session:
  - [ ] where in current Oscar journey can we create features for Navigator (short, intermediate, long term)
  - [ ] What backend / data modeling considerations?
  - [ ] Onboarding of Oscar
  - [ ] Dashboard(?) experience
  - [ ] Update service blueprint with future state (above)
- [ ] Research plan: based on these hypothetical features, how do we validate them with users?
